#!/bin/sh

# function to get ISO 8601 formatted date
get_iso_date() {
    if date -I &> /dev/null; then
        # GNU date (Linux)
        date -Is
    else
        # BSD date (macOS)
        date -u +"%Y-%m-%dT%H:%M:%SZ"
    fi
}

# update last_updated.txt
echo -n $(get_iso_date) > last_updated.txt
git add last_updated.txt
echo "last_updated.txt updated with current date."

# update sitemap.xml
current_date=$(get_iso_date)
cat > sitemap.xml << EOF
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://pages.cs.wisc.edu/~eeshaan/index.html</loc>
    <lastmod>${current_date}</lastmod>
    <priority>1.0</priority>
  </url>
</urlset>
EOF

git add sitemap.xml
echo "sitemap.xml updated with current date."

exit 0